# Generated by Django 5.2.6 on 2025-10-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('window', 'Ventana'), ('aisle', 'Pasillo'), ('middle', 'Centro')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('bus', 'number')},
            },
        ),
    ]
