# Generated by Django 5.2.6 on 2025-10-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
